module MarketplaceKit
  module Services
    class Config
      def load
        @config = {}

        load_config_from '.builder'
        load_config_from '.builder-autogenerated', required: false
      rescue Errno::ENOENT
        raise "Please create .builder file in order to continue."
      end

      def token
        @config["localhost"]['token'].to_s
      end

      def set_token(value)
        @config['localhost']['token'] = value
        save_token(value)
      end

      def url
        @config['localhost']['url'].to_s
      end

      private

      def load_config_from(file_name, options = {})
        return if options[:required] == false && !File.exist?("#{MarketplaceKit.builder_folder}.builder-autogenerated")

        text_config = File.read("#{MarketplaceKit.builder_folder}#{file_name}")
        @config.deeper_merge! JSON.parse(text_config)
      end

      def save_token(value)
        File.write("#{MarketplaceKit.builder_folder}.builder-autogenerated", { localhost: { token: value } }.to_json)
      end
    end
  end
end
