module MarketplaceKit
  module Services
    class Config
      def initialize
        @config = {}
      end

      def load
        raw_config = File.read("#{MarketplaceKit.builder_folder}.builder")
        auto_raw_config = File.read("#{MarketplaceKit.builder_folder}.builder-autogenerated")

        @config = JSON.parse(raw_config).deeper_merge(JSON.parse(auto_raw_config))
      end

      def token
        @config["localhost"]['token'].to_s
      end

      def set_token(value)
        File.write("#{MarketplaceKit.builder_folder}.builder-autogenerated", { localhost: { token: value } }.to_json)

        @config['localhost']['token'] = value
      end

      def url
        @config['localhost']['url'].to_s
      end
    end
  end
end
