#!/usr/bin/env node

const program = require('commander');

program
  .version('0.0.3')
  .command('deploy', 'deploy marketplace').alias('d')
  .command('sync', 'enter sync mode').alias('s')
  .command('remote', 'remote endpoints')
  .parse(process.argv);

if (!program.args.length) program.help();


// fs.open('.builder', 'r', (err, fd) => {
//     if (err) {
//         if (err.code === 'ENOENT') {
//             console.error('myfile does not exist');
//             return;
//         }

//         throw err;
//     }

//     console.log(fd);
// });
