#!/usr/bin/env node

const program = require('commander');

program
  .version('0.0.3')
  .command('add', 'add remote endpoint')
  .command('list', 'list remote endpoints')
  .parse(process.argv);

if (!program.args.length) program.help();
