#!/usr/bin/env node

const program = require('commander');

program
  .version('0.3.0')
  .parse(process.argv);

const list = require('./settings').listEnvironments();

console.log('Available environments:', list.join(", "));
