#!/usr/bin/env node

const program = require('commander');

program
  .version('0.0.3')
  .command('deploy', 'deploy marketplace').alias('d')
  .command('watch', 'enter sync mode').alias('w')
  .command('remote', 'remote endpoints')
  .command('sync', 'remote endpoints')
  .parse(process.argv);

if (!program.args.length) program.help();
