#!/usr/bin/env node

const program = require('commander'),
      version = require("./package.json").version;

program
  .version(version)
  .command('add', 'add remote endpoint')
  .command('list', 'list remote endpoints')
  .parse(process.argv);

if (!program.args.length) program.help();
