#!/usr/bin/env node

const program = require('commander'),
  fs = require('fs'),
  rl = require('readline'),
  request = require('request');

const checkParams = (params) => {
  if (!params.args.length) {
    params.help();
    process.exit(1);
  }
  if (typeof params.email === 'undefined') {
    console.error('no email given!');
    process.exit(1);
  }
  if (typeof params.url === 'undefined') {
    console.error('no URL given!');
    process.exit(1);
  }

  if (params.url.slice(-1) != '/') {
    params.url = params.url + '/'
  }
};

// turn to promise
const getPassword = () => {
  return new Promise((resolve, reject) => {
    const reader = rl.createInterface({ input: process.stdin, output: process.stdout });
    reader.stdoutMuted = true;
    reader.question('Password: ', (password) => {
      reader.close();
      resolve(password);
    });

    reader._writeToOutput = (stringToWrite) => {
      reader.stdoutMuted && reader.output.write('*') || reader.output.write(stringToWrite);
    };
  });
};

const login = (email, password, settings) => {
  request({
    uri: settings.url + 'api/marketplace_builder/sessions',
    method: 'POST',
    json: {email, password}
  }, function (error, response, body) {
    if (!error && response.statusCode == 200 && body.token) {
      storeEndpoint(
        Object.assign(settings, { token: body.token })
      );
    } else {
      console.log('Error')
      console.error(error);
      if (response) console.error(`HTTP Status code: ${response.statusCode}`);
      if (body) console.log(`\nError: ${body.error}`);
      process.exit(1);
    }
  });
};

const storeEndpoint = (settings) => {
  const endpointSettings = {
    [settings.endpoint]: {
      url: settings.url,
      token: settings.token,
      email: settings.email
    }
  };
  saveFile(Object.assign(existingSettings(), endpointSettings));
};

const saveFile = (settings) => {
  fs.writeFileSync(process.env.CONFIG_FILE_PATH, JSON.stringify(settings), (err) => {
    if (err) throw err;
  });
};

const existingSettings = () => {
  if (fs.existsSync(process.env.CONFIG_FILE_PATH)) {
    return JSON.parse(fs.readFileSync(process.env.CONFIG_FILE_PATH));
  } else {
    return {};
  }
};

program
  .version('0.3.0')
  .arguments('<endpoint>', 'endpoint of environment endpoint')
  .option('--email <email>', 'email')
  .option('--url <url>', 'instance endpoint')
  .option('-c --config-file <config-file>', 'config file path', '.marketplace-kit')
  .action((endpoint, params) => {
    process.env.CONFIG_FILE_PATH = params.configFile;
    checkParams(params);
    getPassword().then((password) => {
      const settings = { url: params.url, endpoint: endpoint, email: params.email };
      login(params.email, password, settings);
    });
  });

program.parse(process.argv);
if (!program.args.length) {
  program.help();
  process.exit(1);
}
