describe 'generate config' do
  before do
    allow(MarketplaceKit).to receive(:builder_folder).and_return('tmp')
  end

  let(:files) do
    {
      "#{MarketplaceKit.builder_folder}.builder" => '{
        "localhost": {
          "url": "http://localhost:3000"
        },
        "staging": {
          "url": "http://staging-url.com"
        }
      }'
    }
  end

  it 'add token to empty config' do
    stub_files(files)
    config = MarketplaceKit::Services::Config.new
    config.load('localhost')

    config.set_token('xyz')

    expect(File.read("#{MarketplaceKit.builder_folder}.builder-autogenerated")).to eq('{"localhost":{"token":"xyz"}}')
  end

  it 'adds another token to config' do
    stub_files(files.merge("#{MarketplaceKit.builder_folder}.builder-autogenerated" => '{"staging":{"token":"example-user-token"}}'))
    config = MarketplaceKit::Services::Config.new
    config.load('localhost')

    config.set_token('zzz')
    expect(File.read("#{MarketplaceKit.builder_folder}.builder-autogenerated")).to eq('{"staging":{"token":"example-user-token"},"localhost":{"token":"zzz"}}')
  end
end
